import {Box, Text, useApp, useInput, useStdout} from "ink";
import {useCallback, useEffect, useMemo, useRef, useState} from "react";
import type {ActivityLogEvent, Health, HostnamePlan, HostnameRemovalPlan, Inventory, Tunnel, Zone, ZoneInventory} from "./contracts.js";
import type {TuiOperations} from "./operations.js";
import type {ActivityEvent} from "./activity.js";
import {activityDetails} from "./activity.js";

type Scope = string | null;
type HostnameRequest = {zone: string; hostname: string; type: HostnamePlan["type"]; service: string; originServerName: string | null; verifyTls: boolean};
type HostnameForm = HostnameRequest & {step: "hostname" | "type" | "service" | "tls"};
export type {ActivityEvent} from "./activity.js";
const tunnelKey = (tunnel: Tunnel) => `${tunnel.zone}/${tunnel.name}`;

function logEventToActivity(event: ActivityLogEvent): ActivityEvent {
	const diagnostic = event.context?.diagnostic;
	return {at: event.timestamp.slice(11, 19), id: event.timestamp, type: event.type, level: event.level === "debug" ? "info" : event.level, message: event.message, details: typeof diagnostic === "string" ? activityDetails(diagnostic) : undefined};
}

function visibleLogEvents(events: ActivityLogEvent[]): ActivityEvent[] {
	return events
		.filter(event => !(event.context?.operation === "zone" && event.message === "cftunnel zone completed"))
		.reverse()
		.map(logEventToActivity);
}

export function App({client, onLogin, onApplyHostname, onRemoveHostname, activity: initialActivity = []}: {client: TuiOperations; onLogin?: (zone: string) => Promise<void>; onApplyHostname?: (request: HostnameRequest) => Promise<void>; onRemoveHostname?: (request: {zone: string; hostname: string}) => Promise<void>; activity?: ActivityEvent[]}) {
	const {exit} = useApp(); const {stdout} = useStdout();
	const [inventory, setInventory] = useState<Inventory | null>(null);
	const [zones, setZones] = useState<ZoneInventory | null>(null);
	const [scope, setScope] = useState<Scope>(null); const [zoneCursor, setZoneCursor] = useState<Scope>(null); const [selected, setSelected] = useState(0);
	const [health, setHealth] = useState<Health | null>(null); const [healthKind, setHealthKind] = useState<"tunnel" | "scope" | null>(null); const [busy, setBusy] = useState("Loading local zones and inventory…"); const [error, setError] = useState<string | null>(null);
	const [filter, setFilter] = useState(""); const [filtering, setFiltering] = useState(false); const [compactPanel, setCompactPanel] = useState<"navigation" | "detail">("navigation");
	const [pendingZone, setPendingZone] = useState<string | null>(null); const [pendingAdd, setPendingAdd] = useState<string | null>(null); const [pendingLogin, setPendingLogin] = useState<string | null>(null); const [addingZone, setAddingZone] = useState(false); const [newZone, setNewZone] = useState(""); const [skipZoneConfirmation, setSkipZoneConfirmation] = useState(false); const [rememberChoice, setRememberChoice] = useState(false); const [version, setVersion] = useState<string | null>(null);
	const [hostnameForm, setHostnameForm] = useState<HostnameForm | null>(null); const [pendingHostnamePlan, setPendingHostnamePlan] = useState<HostnamePlan | null>(null);
	const [removingTunnel, setRemovingTunnel] = useState<Tunnel | null>(null); const [removalIndex, setRemovalIndex] = useState(0); const [pendingRemovalPlan, setPendingRemovalPlan] = useState<HostnameRemovalPlan | null>(null);
	const [activity, setActivity] = useState<ActivityEvent[]>(initialActivity); const [activityError, setActivityError] = useState<string | null>(null);
	const selectedKey = useRef<string | null>(null); const filterValue = useRef(filter); const zoneCursorValue = useRef(zoneCursor); const compact = (stdout.columns ?? 120) < 108;
	const allTunnels = inventory?.tunnels ?? []; const tunnels = useMemo(() => filterTunnels(allTunnels, filter), [allTunnels, filter]); const active = tunnels[selected];
	selectedKey.current = active ? tunnelKey(active) : null; filterValue.current = filter; zoneCursorValue.current = zoneCursor;
	const refresh = useCallback(async (requestedScope?: Scope) => {
		setBusy("Refreshing operational inventory…"); setError(null); setHealth(null); setHealthKind(null);
		try { const capabilities = await client.capabilities(); const [, nextZones] = await Promise.all([client.zoneCurrent(), client.zoneList()]); const preferredScope = requestedScope ?? scope; const validScope = preferredScope !== null && nextZones.zones.some(zone => zone.name === preferredScope) ? preferredScope : (nextZones.zones[0]?.name ?? null); const validCursor = zoneCursorValue.current !== null && nextZones.zones.some(zone => zone.name === zoneCursorValue.current) ? zoneCursorValue.current : validScope; const nextInventory = validScope === null ? {scope_zone: null, listed_at: new Date().toISOString(), tunnels: []} : await client.list(validScope); const visible = filterTunnels(nextInventory.tunnels, filterValue.current); const index = selectedKey.current ? visible.findIndex(tunnel => tunnelKey(tunnel) === selectedKey.current) : -1; setVersion(capabilities.application_version); setZones(nextZones); setScope(validScope); setZoneCursor(validCursor); setInventory(nextInventory); setSelected(index >= 0 ? index : 0); if (client.activity) { try { const result = await client.activity(); const warning = client.takeObservabilityWarning?.(); setActivity([...initialActivity, ...visibleLogEvents(result.events)]); setActivityError(warning ?? (result.warnings.length ? result.warnings.join(" · ") : null)); } catch (cause) { const details = cause instanceof Error ? activityDetails(cause.message).join(" · ") : "Query failed for an unknown reason."; setActivityError(client.takeObservabilityWarning?.() ?? `Persistent activity log could not be read: ${details}`); } } }
		catch (cause) { setError(cause instanceof Error ? cause.message : "Unknown operational error"); } finally { setBusy(""); }
	}, [client, scope]);
	useEffect(() => { void refresh(); }, [refresh]);
	const scopeOptions = zones?.zones.map(zone => zone.name) ?? []; const zoneCursorIndex = Math.max(0, zoneCursor === null ? 0 : scopeOptions.indexOf(zoneCursor));
	const summary = useMemo(() => ({active: tunnels.filter(t => t.status === "active").length, bootEnabled: tunnels.filter(t => t.boot_state === "enabled").length, bootDisabled: tunnels.filter(t => t.boot_state === "disabled").length}), [tunnels]);
	const requestScope = (next: string) => { if (next === scope) return; if (skipZoneConfirmation) { void applyScope(next); return; } setRememberChoice(false); setPendingZone(next); };
	const applyScope = async (next: string) => { setBusy(`Setting ${next} as the active zone…`); setError(null); selectedKey.current = null; setSelected(0); setHealth(null); setHealthKind(null); try { await client.zoneUse(next); await refresh(next); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to set the active zone"); setBusy(""); } };
	const startLogin = (zone: string) => { if (!onLogin) { setError("Interactive login is unavailable in this TUI session"); return; } setBusy(`Opening Cloudflare login for ${zone}…`); setError(null); void onLogin(zone); };
	const registerAndLogin = async (zone: string) => { setBusy(`Registering ${zone}…`); setError(null); selectedKey.current = null; setSelected(0); setHealth(null); setHealthKind(null); try { await client.zoneUse(zone); await refresh(zone); startLogin(zone); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to register the zone"); setBusy(""); } };
	const requestHostnamePlan = async (request: HostnameRequest) => { setBusy(`Planning hostname ${request.hostname}…`); setError(null); try { const plan = await client.hostnamePlan(request.zone, request.hostname, request.type, request.service, request.originServerName, request.verifyTls); setPendingHostnamePlan(plan); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to plan hostname"); } finally { setBusy(""); } };
	const applyHostname = (plan: HostnamePlan) => { if (!onApplyHostname || !plan.zone) { setError("Hostname apply is unavailable in this TUI session"); return; } setBusy(`Applying hostname ${plan.hostname}…`); setError(null); void onApplyHostname({zone: plan.zone, hostname: plan.hostname, type: plan.type, service: plan.service, originServerName: plan.origin_tls.server_name, verifyTls: plan.origin_tls.verify}); };
	const requestRemovalPlan = async (tunnel: Tunnel, hostname: string) => { if (!client.hostnameRemovePlan) { setError("This cftunnel version cannot plan hostname removal"); return; } setBusy(`Planning removal of ${hostname}…`); setError(null); try { setPendingRemovalPlan(await client.hostnameRemovePlan(tunnel.zone, hostname)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to plan hostname removal"); } finally { setBusy(""); } };
	const applyRemoval = (plan: HostnameRemovalPlan) => { if (!onRemoveHostname) { setError("Hostname removal is unavailable in this TUI session"); return; } setBusy(`Removing hostname ${plan.hostname}…`); setError(null); void onRemoveHostname({zone: plan.zone, hostname: plan.hostname}); };
	const checkHealth = (name?: string, zone?: Scope, kind: "tunnel" | "scope" = name ? "tunnel" : "scope") => { if (zone === null) return; const label = name ? `Checking health for tunnel ${name}…` : `Checking health for scope ${zone}…`; setBusy(label); setError(null); setHealthKind(kind); void client.health(name, zone).then(setHealth).catch(cause => setError(cause instanceof Error ? cause.message : "Health check failed")).finally(async () => { const warning = client.takeObservabilityWarning?.(); if (warning) setActivityError(warning); if (client.activity) { try { const result = await client.activity(); setActivity([...initialActivity, ...visibleLogEvents(result.events)]); if (result.warnings.length) setActivityError(result.warnings.join(" · ")); } catch { setActivityError("Persistent activity log could not be read."); } } setBusy(""); }); };
	useInput((input, key) => {
		if (pendingZone) { if (key.escape) { setPendingZone(null); return; } if (input === " ") { setRememberChoice(value => !value); return; } if (key.return) { const next = pendingZone; setPendingZone(null); if (rememberChoice) setSkipZoneConfirmation(true); void applyScope(next); } return; }
		if (pendingHostnamePlan) { if (key.escape) { setPendingHostnamePlan(null); return; } if (key.return) { const plan = pendingHostnamePlan; setPendingHostnamePlan(null); applyHostname(plan); } return; }
		if (pendingRemovalPlan) { if (key.escape) { setPendingRemovalPlan(null); return; } if (key.return) { const plan = pendingRemovalPlan; setPendingRemovalPlan(null); applyRemoval(plan); } return; }
		if (removingTunnel) { if (key.escape) { setRemovingTunnel(null); return; } if (key.upArrow) setRemovalIndex(index => Math.max(0, index - 1)); else if (key.downArrow) setRemovalIndex(index => Math.min(removingTunnel.routes.length - 1, index + 1)); else if (key.return) { const route = removingTunnel.routes[removalIndex]; setRemovingTunnel(null); if (route) void requestRemovalPlan(removingTunnel, route.hostname); } return; }
		if (pendingAdd) { if (key.escape) { setPendingAdd(null); return; } if (key.return) { const next = pendingAdd; setPendingAdd(null); void registerAndLogin(next); } return; }
		if (pendingLogin) { if (key.escape) { setPendingLogin(null); return; } if (key.return) { const next = pendingLogin; setPendingLogin(null); startLogin(next); } return; }
		if (hostnameForm) { if (key.escape) { setHostnameForm(null); return; } if (hostnameForm.step === "type") { const types: HostnamePlan["type"][] = ["http", "ssh", "tcp"]; const index = types.indexOf(hostnameForm.type); if (key.leftArrow || key.upArrow) setHostnameForm({...hostnameForm, type: types[(index + types.length - 1) % types.length] ?? "http"}); else if (key.rightArrow || key.downArrow) setHostnameForm({...hostnameForm, type: types[(index + 1) % types.length] ?? "http"}); else if (key.return) setHostnameForm({...hostnameForm, step: "service"}); return; } if (hostnameForm.step === "tls") { if (input === "s") setHostnameForm({...hostnameForm, originServerName: hostnameForm.originServerName ? null : hostnameForm.hostname}); else if (input === "v") setHostnameForm({...hostnameForm, verifyTls: !hostnameForm.verifyTls}); else if (key.return) { const request = hostnameForm; setHostnameForm(null); void requestHostnamePlan(request); } return; } if (key.return) { if (hostnameForm.step === "hostname") { const hostname = hostnameForScope(hostnameForm.hostname, hostnameForm.zone); if (!hostname) { setError("Enter a hostname label, @, *, or a hostname in the current Scope"); return; } setHostnameForm({...hostnameForm, hostname, step: "type"}); } else if (hostnameForm.service.trim()) { const request = {...hostnameForm, service: hostnameForm.service.trim()}; if (request.service.startsWith("https://") && request.type === "http") setHostnameForm({...request, step: "tls"}); else { setHostnameForm(null); void requestHostnamePlan(request); } } else setError("Enter a local origin service URL"); return; } if (key.backspace || key.delete) { if (hostnameForm.step === "hostname") setHostnameForm({...hostnameForm, hostname: hostnameForm.hostname.slice(0, -1)}); else setHostnameForm({...hostnameForm, service: hostnameForm.service.slice(0, -1)}); return; } if (input && !key.ctrl && !key.meta) { if (hostnameForm.step === "hostname") setHostnameForm({...hostnameForm, hostname: hostnameForm.hostname + input}); else setHostnameForm({...hostnameForm, service: hostnameForm.service + input}); } return; }
		if (addingZone) { if (key.escape) { setAddingZone(false); setNewZone(""); return; } if (key.return) { const next = newZone.trim(); if (next) { setAddingZone(false); setNewZone(""); setPendingAdd(next); } else setError("Enter a Cloudflare zone, such as example.com"); return; } if (key.backspace || key.delete) { setNewZone(value => value.slice(0, -1)); return; } if (input && !key.ctrl && !key.meta) setNewZone(value => value + input); return; }
		if (filtering) { if (key.escape || key.return) { setFiltering(false); return; } if (key.backspace || key.delete) { setFilter(value => value.slice(0, -1)); return; } if (input && !key.ctrl && !key.meta) setFilter(value => value + input); return; }
		if (input === "q" || (key.ctrl && input === "c")) exit(); if (input === "r") void refresh(); if (input === "a") { setError(null); setAddingZone(true); return; } if (input === "l" && scope) { setError(null); setPendingLogin(scope); return; } if (input === "n" && scope) { const zone = zones?.zones.find(item => item.name === scope); if (zone?.credential.state !== "ready") { setError("Authenticate this Scope before adding a hostname ([l] login)"); return; } setError(null); setHostnameForm({zone: scope, hostname: "", type: "http", service: "", originServerName: null, verifyTls: true, step: "hostname"}); return; } if (input === "x" && active && active.routes.length) { setError(null); setRemovalIndex(0); setRemovingTunnel(active); return; } if (input === "/") { setFiltering(true); return; } if (key.tab && compact) { setCompactPanel(panel => panel === "navigation" ? "detail" : "navigation"); return; } if (key.escape) { setFilter(""); return; }
		if (key.rightArrow && zoneCursorIndex < scopeOptions.length - 1) { const next = scopeOptions[zoneCursorIndex + 1]; if (next !== undefined) setZoneCursor(next); }
		if (key.leftArrow && zoneCursorIndex > 0) { const previous = scopeOptions[zoneCursorIndex - 1]; if (previous !== undefined) setZoneCursor(previous); }
		if (key.return && zoneCursor && zoneCursor !== scope) requestScope(zoneCursor);
		if (key.downArrow && selected < tunnels.length - 1) setSelected(selected + 1); if (key.upArrow && selected > 0) setSelected(selected - 1);
		if (input === "h" && active) checkHealth(active.name, active.zone, "tunnel"); if (input === "H") checkHealth(undefined, scope, "scope");
	});
	const selectedZone = scope === null ? null : zones?.zones.find(item => item.name === scope);
	const detail = tunnels.length === 0 && !busy ? <EmptyState zone={selectedZone} filter={filter}/> : active && <TunnelDetail tunnel={active} health={health}/>;
	return <Box flexDirection="column" paddingX={1}>
		<Header scope={scope} version={version} listedAt={inventory?.listed_at ?? null}/>
		<Summary summary={summary} total={tunnels.length}/>
		{filter && <Banner color="cyan">{`Filter: ${filter}  (Esc clears)`}</Banner>}
		{busy && <Banner color="yellow">{`◌ ${busy}`}</Banner>}
		{error && <Banner color="red">{`! ${error}`}</Banner>}
		{health && healthKind && <HealthSummary health={health} kind={healthKind}/>}
		<Box flexDirection={compact ? "column" : "row"} gap={1}>{!compact ? <><Sidebar zones={zones?.zones ?? []} scope={scope} cursor={zoneCursor} tunnels={tunnels} selected={selected}/>{detail}</> : compactPanel === "navigation" ? <Sidebar zones={zones?.zones ?? []} scope={scope} cursor={zoneCursor} tunnels={tunnels} selected={selected}/> : detail}</Box>
		<ActivityPanel activity={activity} error={activityError}/>
		<Footer filtering={filtering} compact={compact} panel={compactPanel}/>
		{addingZone && <ZoneInput value={newZone}/>}
		{hostnameForm && <HostnameInput form={hostnameForm}/>}
		{pendingHostnamePlan && <HostnamePlanConfirmation plan={pendingHostnamePlan}/>}
		{removingTunnel && <HostnameRemovalSelect tunnel={removingTunnel} selected={removalIndex}/>}
		{pendingRemovalPlan && <HostnameRemovalConfirmation plan={pendingRemovalPlan}/>}
		{pendingZone && <ZoneConfirmation current={scope} next={pendingZone} remember={rememberChoice}/>}
		{pendingAdd && <ZoneActionConfirmation action="add" zone={pendingAdd}/>}
		{pendingLogin && <ZoneActionConfirmation action="login" zone={pendingLogin}/>}
	</Box>;
}

function Header({scope, version, listedAt}: {scope: Scope; version: string | null; listedAt: string | null}) { return <Box borderStyle="round" borderColor="cyan" paddingX={1} flexDirection="column"><Box justifyContent="space-between"><Box><Text bold color="cyan">CFTUNNEL</Text><Text dimColor>{`  Operational dashboard${version ? ` · v${version}` : ""}`}</Text></Box><Text>Scope: <Text color="magenta">{scope ?? "no registered zone"}</Text></Text></Box><Text dimColor>{`Inventory: local YAML + current systemd query${listedAt ? ` · ${listedAt}` : ""}`}</Text></Box>; }
function Summary({summary, total}: {summary: {active: number; bootEnabled: number; bootDisabled: number}; total: number}) { return <Box gap={1} marginY={1}><Metric label="TUNNELS" value={total} color="cyan"/><Metric label="RUNNING NOW" value={summary.active} color="green"/><Metric label="BOOT ENABLED" value={summary.bootEnabled} color="yellow"/><Metric label="BOOT DISABLED" value={summary.bootDisabled} color="gray"/></Box>; }
function Metric({label, value, color}: {label: string; value: number; color: "cyan" | "green" | "yellow" | "gray"}) { return <Box borderStyle="round" borderColor={color} paddingX={1}><Text color={color} bold>{value} </Text><Text dimColor>{label}</Text></Box>; }
function Banner({children, color}: {children: string; color: "cyan" | "yellow" | "red"}) { return <Box borderStyle="round" borderColor={color} paddingX={1} marginBottom={1}><Text color={color}>{children}</Text></Box>; }
function HealthSummary({health, kind}: {health: Health; kind: "tunnel" | "scope"}) { return <Box marginBottom={1}><Text color="yellow">{kind === "scope" ? "SCOPE HEALTH" : "TUNNEL HEALTH"} · completed at {health.checked_at} · {health.tunnels.length} tunnel{health.tunnels.length === 1 ? "" : "s"} checked</Text></Box>; }
function ActivityPanel({activity, error}: {activity: ActivityEvent[]; error: string | null}) { if (activity.length === 0 && !error) return null; return <Box borderStyle="round" borderColor={error ? "yellow" : "gray"} flexDirection="column" marginTop={1} paddingX={1}><Text bold>ACTIVITY · PERSISTENT LOCAL LOG</Text>{error && <Text color="yellow">Observability warning: {error}</Text>}{activity.slice(-4).map((event, index) => <Box key={`${event.id ?? event.at}-${event.type}-${event.message}-${index}`} flexDirection="column"><Text color={event.level === "error" ? "red" : event.level === "success" ? "green" : event.level === "warning" ? "yellow" : "cyan"}>{`[${event.at}][${(event.type ?? "activity").toUpperCase()}] ${event.level === "error" ? "✗" : event.level === "success" ? "✓" : event.level === "warning" ? "!" : "·"} ${event.message}`}</Text>{event.details?.map((detail, detailIndex) => <Text key={`${detailIndex}-${detail}`} dimColor color={event.level === "error" ? "red" : undefined}>{`  ${detail}`}</Text>)}</Box>)}</Box>; }
function Sidebar({zones, scope, cursor, tunnels, selected}: {zones: Zone[]; scope: Scope; cursor: Scope; tunnels: Tunnel[]; selected: number}) { return <Box flexDirection="column" width={43} flexShrink={0} gap={1}><Box borderStyle="round" borderColor="magenta" flexDirection="column" paddingX={1}><Text bold color="magenta">ZONES</Text>{zones.map(zone => <Box key={zone.name} flexDirection="column"><Text inverse={cursor === zone.name} color={credentialColor(zone.credential.state)}>{cursor === zone.name ? "›" : " "} {credentialIcon(zone.credential.state)} {zone.name}{scope === zone.name ? " [scope]" : ""}</Text><Text dimColor>{`    ${zone.tunnel_count} tunnels · ${zone.route_count} routes · credential ${credentialLabel(zone.credential.state)}`}</Text></Box>)}</Box><Box borderStyle="round" borderColor="blue" flexDirection="column" paddingX={1}><Text bold color="blue">TUNNELS · CURRENT SCOPE</Text>{tunnels.length === 0 ? <Text dimColor>None in this scope</Text> : tunnels.map((tunnel, index) => <Box key={tunnelKey(tunnel)} flexDirection="column"><Text inverse={index === selected} color={statusColor(tunnel.config.issues.length ? "failed" : tunnel.status)}>{index === selected ? "›" : " "} {statusIcon(tunnel.config.issues.length ? "failed" : tunnel.status)} {tunnel.name}</Text><Text dimColor>{`    now ${runtimeLabel(tunnel.status)} · ${bootStateIcon(tunnel.boot_state)} boot ${bootStateLabel(tunnel.boot_state)}`}</Text></Box>)}</Box><Legend/></Box>; }
function Legend() { return <Box borderStyle="round" borderColor="gray" flexDirection="column" paddingX={1}><Text bold>STATUS KEY</Text><Text bold color="magenta">ZONE CREDENTIAL</Text><Text dimColor>✓ bound · ? unverified · ! invalid</Text><Text bold color="blue">SERVICE NOW</Text><Text dimColor>● running · ○ stopped · × failed · ? unavailable</Text><Text bold color="yellow">STARTUP AT BOOT</Text><Text dimColor>↻ enabled · ◌ this boot only</Text><Text dimColor>— disabled · ? other/unknown</Text></Box>; }
function TunnelDetail({tunnel, health}: {tunnel: Tunnel; health: Health | null}) { const entry = health?.tunnels.find(item => item.name === tunnel.name && item.zone === tunnel.zone); const disabledAtBoot = tunnel.boot_state === "disabled"; return <Box borderStyle="round" borderColor="green" flexDirection="column" paddingX={1} flexGrow={1}><Box justifyContent="space-between"><Text bold>DETAILS · {tunnel.name}</Text><Text color={statusColor(tunnel.status)}>{statusIcon(tunnel.status)} {runtimeLabel(tunnel.status).toUpperCase()}</Text></Box><Text dimColor>{tunnel.zone} · {tunnel.unit}</Text><Box marginTop={1}><Text bold>Local configuration</Text></Box><Text>YAML: <State value={tunnel.config.yaml.present} detail={tunnel.config.yaml.mode}/>{`  credential JSON: `}<State value={tunnel.config.credential.present} detail={tunnel.config.credential.mode}/></Text><Text>Service now: <Text color={statusColor(tunnel.status)}>{runtimeLabel(tunnel.status)}</Text> · Startup at boot: <Text color={bootStateColor(tunnel.boot_state)}>{bootStateIcon(tunnel.boot_state)} {bootStateLabel(tunnel.boot_state)}</Text></Text><Text>UUID: {tunnel.uuid ?? "unresolved"} · {tunnel.routes.length} routes</Text>{disabledAtBoot && <Box borderStyle="single" borderColor="yellow" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="yellow">STARTUP WARNING</Text><Text>{tunnel.status === "active" ? "This service is running now, but will not start automatically after a reboot." : "This service is disabled and will not start automatically after a reboot."}</Text><Text dimColor>{`Enable it with: sudo systemctl enable ${tunnel.unit}`}</Text></Box>}<Diagnosis tunnel={tunnel}/><Box marginTop={1}><Text bold>Routes</Text></Box>{tunnel.routes.map(route => <Box key={route.hostname}><Text color="cyan">{route.hostname}</Text><Text dimColor>  →  {route.service}</Text></Box>)}{entry ? <HealthPanel entry={entry} checkedAt={health?.checked_at ?? ""}/> : <Box marginTop={1}><Text dimColor>Press h for this tunnel or H for the current scope health check.</Text></Box>}</Box>; }
function State({value, detail}: {value: boolean; detail: string | null}) { return <Text color={value ? "green" : "red"}>{value ? `present${detail ? ` (${detail})` : ""}` : "missing"}</Text>; }
function Diagnosis({tunnel}: {tunnel: Tunnel}) { const issues = [...tunnel.config.issues]; if (!tunnel.config.credential.present) issues.push("Restore the private tunnel credential file before starting this unit."); if (tunnel.status === "inactive" || tunnel.status === "enabled") issues.push(`Unit is stopped — inspect: cftunnel --zone ${tunnel.zone} status --name ${tunnel.name}`); if (tunnel.status === "failed" || tunnel.status === "unavailable") issues.push("Local systemd status could not be considered healthy; inspect the host service manager."); if (tunnel.boot_state === "enabled-runtime" || tunnel.boot_state === "linked-runtime") issues.push("Unit is enabled only for this boot; enable it persistently to survive a reboot."); if (tunnel.boot_state === "masked" || tunnel.boot_state === "masked-runtime") issues.push("Unit is masked and cannot be started until it is unmasked."); if (issues.length === 0) return null; return <Box borderStyle="single" borderColor="yellow" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="yellow">ATTENTION</Text>{[...new Set(issues)].map(issue => <Text key={issue}>{issue}</Text>)}</Box>; }
function HealthPanel({entry, checkedAt}: {entry: Health["tunnels"][number]; checkedAt: string}) { return <Box borderStyle="single" borderColor="yellow" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="yellow">HEALTH · {checkedAt}</Text><Text>Service now: <Text color={statusColor(entry.systemd.status)}>{runtimeLabel(entry.systemd.status)}</Text> · Startup at boot: <Text color={bootStateColor(entry.systemd.boot_state)}>{bootStateIcon(entry.systemd.boot_state)} {bootStateLabel(entry.systemd.boot_state)}</Text> · credential: {entry.config.credential.present ? "present" : "missing"}</Text>{entry.routes.map(route => <Box key={route.hostname} flexDirection="column"><Text>DNS {route.hostname}: <Text color={route.dns.result ? "green" : "red"}>{route.dns.result ?? "unresolved"}</Text></Text>{!route.dns.result && <Text dimColor>{`Inspect: cftunnel --zone ${entry.zone} health --name ${entry.name}`}</Text>}</Box>)}</Box>; }
function EmptyState({zone, filter}: {zone: Zone | undefined | null; filter: string}) { if (filter && zone && zone.name.toLowerCase().includes(filter.toLowerCase())) return <Box borderStyle="round" borderColor="gray" paddingX={1} flexGrow={1} flexDirection="column"><Text bold>{zone.name}</Text><Text dimColor>{`Zone matches “${filter}”, but it has no local tunnels.`}</Text></Box>; if (filter) return <Box borderStyle="round" borderColor="gray" paddingX={1} flexGrow={1}><Text dimColor>No tunnel or zone matches the current filter in this scope.</Text></Box>; if (!zone) return <Box borderStyle="round" borderColor="gray" paddingX={1} flexGrow={1}><Text dimColor>No local tunnel routes found across registered zones.</Text></Box>; return <Box borderStyle="round" borderColor="gray" paddingX={1} flexGrow={1} flexDirection="column"><Text bold>{zone.name}</Text><Text dimColor>{`Registered zone · credential ${zone.credential.state} · no local tunnels configured.`}</Text></Box>; }
function ZoneConfirmation({current, next, remember}: {current: Scope; next: string; remember: boolean}) { return <Box borderStyle="double" borderColor="yellow" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="yellow">CHANGE ACTIVE ZONE</Text><Text>{`Current Scope: ${current ?? "none"}`}</Text><Text>{`New Scope:     ${next}`}</Text><Text>This also changes the CLI default zone.</Text><Text color="cyan">{`${remember ? "[x]" : "[ ]"} Do not ask again in this session (Space toggles)`}</Text><Text dimColor>[Enter] Confirm and set zone  [Esc] Cancel</Text></Box>; }
function ZoneInput({value}: {value: string}) { return <Box borderStyle="double" borderColor="cyan" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="cyan">ADD CLOUDFLARE ZONE</Text><Text>Enter the registered Cloudflare zone, not a host or route.</Text><Text color="cyan">{`Zone: ${value}▌`}</Text><Text dimColor>[Enter] Continue  [Esc] Cancel</Text></Box>; }
function ZoneActionConfirmation({action, zone}: {action: "add" | "login"; zone: string}) { const add = action === "add"; return <Box borderStyle="double" borderColor="yellow" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="yellow">{add ? "ADD ZONE AND LOGIN" : "LOGIN TO ACTIVE ZONE"}</Text>{add ? <><Text>{`cftunnel zone use ${zone}`}</Text><Text dimColor>Register and set the default zone</Text><Text>{`Then: cftunnel --zone ${zone} zone login`}</Text><Text dimColor>Authenticate and save a credential to the active zone</Text></> : <><Text>{`cftunnel --zone ${zone} zone login`}</Text><Text dimColor>Authenticate and save a credential to the active zone</Text></>}<Text>{add ? "Registers the zone, makes it the Scope/default, then opens browser authentication." : "Opens browser authentication for the current Scope."}</Text><Text dimColor>[Enter] Confirm  [Esc] Cancel</Text></Box>; }
function HostnameInput({form}: {form: HostnameForm}) { if (form.step === "tls") return <Box borderStyle="double" borderColor="cyan" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="cyan">ORIGIN TLS · {form.hostname}</Text><Text>{`${form.originServerName ? "[x]" : "[ ]"} [s] Send public hostname as SNI (${form.hostname})`}</Text><Text>{`${form.verifyTls ? "[x]" : "[ ]"} [v] Verify the origin certificate${form.verifyTls ? "" : " — accepts any certificate"}`}</Text><Text dimColor>[Enter] Review plan  [Esc] Cancel</Text></Box>; const labels = {hostname: "Hostname label (@ for apex, * for wildcard)", type: "Type", service: "Origin service URL"}; const value = form.step === "hostname" ? form.hostname : form.step === "type" ? form.type : form.service; return <Box borderStyle="double" borderColor="cyan" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="cyan">ADD HOSTNAME · {form.zone}</Text><Text>{labels[form.step]}</Text><Text color="cyan">{form.step === "type" ? `${value}  (Left/Right changes)` : `${value}▌`}</Text><Text dimColor>[Enter] Continue  [Esc] Cancel</Text></Box>; }
function HostnamePlanConfirmation({plan}: {plan: HostnamePlan}) { return <Box borderStyle="double" borderColor="yellow" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="yellow">ADD HOSTNAME PLAN</Text><Text>{`${plan.hostname} · ${plan.type.toUpperCase()} → ${plan.service}`}</Text><Text>{`Tunnel: ${plan.tunnel_name}${plan.existing_tunnel ? " (recommended existing tunnel)" : " (new tunnel)"}`}</Text>{plan.service.startsWith("https://") && <><Text bold>Origin TLS</Text><Text>{`SNI: ${plan.origin_tls.server_name ?? "service URL hostname"} · certificate: ${plan.origin_tls.verify ? "verify" : "DO NOT VERIFY"}`}</Text></>}<Text>{plan.restart_required ? `Will restart ${plan.unit} to load updated ingress.` : `Will start ${plan.unit}.`}</Text><Text>Effects: validate ingress, create/update DNS, and require sudo.</Text>{plan.type === "ssh" && <Text color="yellow">Clients connect with: cloudflared access ssh --hostname {plan.hostname}</Text>}{plan.type === "tcp" && <Text color="yellow">Clients need cloudflared access tcp before connecting.</Text>}<Text dimColor>[Enter] Apply  [Esc] Cancel</Text></Box>; }
function HostnameRemovalSelect({tunnel, selected}: {tunnel: Tunnel; selected: number}) { return <Box borderStyle="double" borderColor="red" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="red">REMOVE HOSTNAME · {tunnel.name}</Text>{tunnel.routes.map((route, index) => <Text key={route.hostname} inverse={index === selected}>{index === selected ? "›" : " "} {route.hostname} → {route.service}</Text>)}<Text dimColor>[↑↓] select  [Enter] review plan  [Esc] cancel</Text></Box>; }
function HostnameRemovalConfirmation({plan}: {plan: HostnameRemovalPlan}) { return <Box borderStyle="double" borderColor="red" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="red">REMOVE HOSTNAME PLAN</Text><Text>{`Remove: ${plan.hostname} from ${plan.tunnel_name}`}</Text><Text>{`${plan.remaining_hostname_count} hostname${plan.remaining_hostname_count === 1 ? "" : "s"} will remain on this tunnel.`}</Text><Text>Effects: update local ingress and restart the service.</Text><Text color="yellow">DNS is unchanged. Record deletion is a separate operation.</Text><Text dimColor>[Enter] Remove hostname  [Esc] Cancel</Text></Box>; }
function Footer({filtering, compact, panel}: {filtering: boolean; compact: boolean; panel: "navigation" | "detail"}) { return <Box marginTop={1}><Text dimColor>{filtering ? "Type to filter by zone, name, hostname, or state · Enter accepts · Esc clears" : `${compact ? `[Tab] ${panel === "navigation" ? "details" : "navigation"}  ` : ""}[a] add zone [n] add hostname [x] remove hostname [l] login [←→] browse zones [Enter] set Scope [↑↓] tunnel [h] tunnel health [H] scope health [/] filter [r] refresh [q] quit`}</Text></Box>; }
function hostnameForScope(value: string, zone: string) { const hostname = value.trim().toLowerCase(); if (!hostname) return ""; if (hostname === "@") return zone; if (hostname === "*") return `*.${zone}`; if (hostname.includes(".")) return hostname; return `${hostname}.${zone}`; }
function filterTunnels(tunnels: Tunnel[], filter: string) { const terms = filter.toLowerCase().trim().split(/\s+/).filter(Boolean); return tunnels.filter(tunnel => terms.every(term => [tunnel.zone, tunnel.name, tunnel.status, tunnel.boot_state, ...tunnel.routes.map(route => route.hostname)].some(value => value.toLowerCase().includes(term)))); }
function statusColor(status: string): "green" | "yellow" | "gray" | "red" { if (status === "active") return "green"; if (status === "failed" || status === "unavailable") return "red"; return "gray"; }
function statusIcon(status: string) { return status === "active" ? "●" : status === "failed" ? "×" : status === "unavailable" ? "?" : "○"; }
function runtimeLabel(status: string) { if (status === "active") return "running"; if (status === "failed") return "failed"; if (status === "unavailable") return "unavailable"; return "stopped"; }
function bootStateLabel(state: string) { const labels: Record<string, string> = {enabled: "enabled", "enabled-runtime": "current boot only", disabled: "disabled", static: "static", indirect: "indirect", masked: "masked", "masked-runtime": "masked this boot", generated: "generated", transient: "transient", linked: "linked", "linked-runtime": "linked this boot", alias: "alias", "bad-setting": "invalid unit config", "not-found": "unit missing", unavailable: "unavailable", unknown: "unknown"}; return labels[state] ?? "unknown"; }
function bootStateIcon(state: string) { return state === "enabled" ? "↻" : state === "enabled-runtime" || state === "linked-runtime" ? "◌" : state === "disabled" ? "—" : state === "masked" || state === "masked-runtime" ? "×" : "?"; }
function bootStateColor(state: string): "green" | "yellow" | "gray" | "red" { if (state === "enabled") return "green"; if (state === "disabled" || state === "masked" || state === "masked-runtime" || state === "bad-setting" || state === "not-found") return "red"; if (state === "enabled-runtime" || state === "linked-runtime") return "yellow"; return "gray"; }
function credentialColor(state: Zone["credential"]["state"]): "green" | "yellow" | "red" { return state === "ready" ? "green" : state === "missing" ? "yellow" : "red"; }
function credentialIcon(state: Zone["credential"]["state"]) { return state === "ready" ? "✓" : state === "missing" ? "?" : "!"; }
function credentialLabel(state: Zone["credential"]["state"]) { return state === "ready" ? "bound" : state === "missing" ? "unverified" : "invalid"; }
