import {Box, Text, useApp, useInput, useStdout} from "ink";
import {useCallback, useEffect, useMemo, useRef, useState} from "react";
import type {Health, Inventory, Tunnel, Zone, ZoneInventory} from "./contracts.js";
import type {TuiOperations} from "./operations.js";

type Scope = string | null;
const tunnelKey = (tunnel: Tunnel) => `${tunnel.zone}/${tunnel.name}`;

export function App({client, onLogin}: {client: TuiOperations; onLogin?: (zone: string) => Promise<void>}) {
	const {exit} = useApp(); const {stdout} = useStdout();
	const [inventory, setInventory] = useState<Inventory | null>(null);
	const [zones, setZones] = useState<ZoneInventory | null>(null);
	const [scope, setScope] = useState<Scope>(null); const [selected, setSelected] = useState(0);
	const [health, setHealth] = useState<Health | null>(null); const [healthKind, setHealthKind] = useState<"tunnel" | "scope" | null>(null); const [busy, setBusy] = useState("Loading local zones and inventory…"); const [error, setError] = useState<string | null>(null);
	const [filter, setFilter] = useState(""); const [filtering, setFiltering] = useState(false); const [compactPanel, setCompactPanel] = useState<"navigation" | "detail">("navigation");
	const [pendingZone, setPendingZone] = useState<string | null>(null); const [pendingAdd, setPendingAdd] = useState<string | null>(null); const [pendingLogin, setPendingLogin] = useState<string | null>(null); const [addingZone, setAddingZone] = useState(false); const [newZone, setNewZone] = useState(""); const [skipZoneConfirmation, setSkipZoneConfirmation] = useState(false); const [rememberChoice, setRememberChoice] = useState(false); const [version, setVersion] = useState<string | null>(null);
	const selectedKey = useRef<string | null>(null); const filterValue = useRef(filter); const compact = (stdout.columns ?? 120) < 108;
	const allTunnels = inventory?.tunnels ?? []; const tunnels = useMemo(() => filterTunnels(allTunnels, filter), [allTunnels, filter]); const active = tunnels[selected];
	selectedKey.current = active ? tunnelKey(active) : null; filterValue.current = filter;
	const refresh = useCallback(async (requestedScope?: Scope) => {
		setBusy("Refreshing operational inventory…"); setError(null); setHealth(null); setHealthKind(null);
		try { const capabilities = await client.capabilities(); const [, nextZones] = await Promise.all([client.zoneCurrent(), client.zoneList()]); const preferredScope = requestedScope ?? scope; const validScope = preferredScope !== null && nextZones.zones.some(zone => zone.name === preferredScope) ? preferredScope : (nextZones.zones[0]?.name ?? null); const nextInventory = validScope === null ? {scope_zone: null, listed_at: new Date().toISOString(), tunnels: []} : await client.list(validScope); const visible = filterTunnels(nextInventory.tunnels, filterValue.current); const index = selectedKey.current ? visible.findIndex(tunnel => tunnelKey(tunnel) === selectedKey.current) : -1; setVersion(capabilities.application_version); setZones(nextZones); setScope(validScope); setInventory(nextInventory); setSelected(index >= 0 ? index : 0); }
		catch (cause) { setError(cause instanceof Error ? cause.message : "Unknown operational error"); } finally { setBusy(""); }
	}, [client, scope]);
	useEffect(() => { void refresh(); }, [refresh]);
	const scopeOptions = zones?.zones.map(zone => zone.name) ?? []; const scopeIndex = Math.max(0, scope === null ? 0 : scopeOptions.indexOf(scope));
	const summary = useMemo(() => ({active: tunnels.filter(t => t.status === "active").length, enabled: tunnels.filter(t => t.status === "enabled").length, inactive: tunnels.filter(t => t.status === "inactive").length}), [tunnels]);
	const requestScope = (next: string) => { if (next === scope) return; if (skipZoneConfirmation) { void applyScope(next); return; } setRememberChoice(false); setPendingZone(next); };
	const applyScope = async (next: string) => { setBusy(`Setting ${next} as the active zone…`); setError(null); selectedKey.current = null; setSelected(0); setHealth(null); setHealthKind(null); try { await client.zoneUse(next); await refresh(next); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to set the active zone"); setBusy(""); } };
	const startLogin = (zone: string) => { if (!onLogin) { setError("Interactive login is unavailable in this TUI session"); return; } setBusy(`Opening Cloudflare login for ${zone}…`); setError(null); void onLogin(zone); };
	const registerAndLogin = async (zone: string) => { setBusy(`Registering ${zone}…`); setError(null); selectedKey.current = null; setSelected(0); setHealth(null); setHealthKind(null); try { await client.zoneUse(zone); await refresh(zone); startLogin(zone); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to register the zone"); setBusy(""); } };
	const checkHealth = (name?: string, zone?: Scope, kind: "tunnel" | "scope" = name ? "tunnel" : "scope") => { if (zone === null) return; const label = name ? `Checking health for tunnel ${name}…` : `Checking health for scope ${zone}…`; setBusy(label); setError(null); setHealthKind(kind); void client.health(name, zone).then(setHealth).catch(cause => setError(cause instanceof Error ? cause.message : "Health check failed")).finally(() => setBusy("")); };
	useInput((input, key) => {
		if (pendingZone) { if (key.escape) { setPendingZone(null); return; } if (input === " ") { setRememberChoice(value => !value); return; } if (key.return) { const next = pendingZone; setPendingZone(null); if (rememberChoice) setSkipZoneConfirmation(true); void applyScope(next); } return; }
		if (pendingAdd) { if (key.escape) { setPendingAdd(null); return; } if (key.return) { const next = pendingAdd; setPendingAdd(null); void registerAndLogin(next); } return; }
		if (pendingLogin) { if (key.escape) { setPendingLogin(null); return; } if (key.return) { const next = pendingLogin; setPendingLogin(null); startLogin(next); } return; }
		if (addingZone) { if (key.escape) { setAddingZone(false); setNewZone(""); return; } if (key.return) { const next = newZone.trim(); if (next) { setAddingZone(false); setNewZone(""); setPendingAdd(next); } else setError("Enter a Cloudflare zone, such as example.com"); return; } if (key.backspace || key.delete) { setNewZone(value => value.slice(0, -1)); return; } if (input && !key.ctrl && !key.meta) setNewZone(value => value + input); return; }
		if (filtering) { if (key.escape || key.return) { setFiltering(false); return; } if (key.backspace || key.delete) { setFilter(value => value.slice(0, -1)); return; } if (input && !key.ctrl && !key.meta) setFilter(value => value + input); return; }
		if (input === "q" || (key.ctrl && input === "c")) exit(); if (input === "r") void refresh(); if (input === "a") { setError(null); setAddingZone(true); return; } if (input === "l" && scope) { setError(null); setPendingLogin(scope); return; } if (input === "/") { setFiltering(true); return; } if (key.tab && compact) { setCompactPanel(panel => panel === "navigation" ? "detail" : "navigation"); return; } if (key.escape) { setFilter(""); return; }
		if (key.rightArrow && scopeIndex < scopeOptions.length - 1) { const next = scopeOptions[scopeIndex + 1]; if (next !== undefined) requestScope(next); }
		if (key.leftArrow && scopeIndex > 0) { const previous = scopeOptions[scopeIndex - 1]; if (previous !== undefined) requestScope(previous); }
		if (key.downArrow && selected < tunnels.length - 1) setSelected(selected + 1); if (key.upArrow && selected > 0) setSelected(selected - 1);
		if (input === "h" && active) checkHealth(active.name, active.zone, "tunnel"); if (input === "H") checkHealth(undefined, scope, "scope");
	});
	const selectedZone = scope === null ? null : zones?.zones.find(item => item.name === scope);
	const detail = tunnels.length === 0 && !busy ? <EmptyState zone={selectedZone} filter={filter}/> : active && <TunnelDetail tunnel={active} health={health}/>;
	return <Box flexDirection="column" paddingX={1}><Header scope={scope} version={version} listedAt={inventory?.listed_at ?? null}/><Summary summary={summary} total={tunnels.length}/>{filter && <Banner color="cyan">{`Filter: ${filter}  (Esc clears)`}</Banner>}{busy && <Banner color="yellow">{`◌ ${busy}`}</Banner>}{error && <Banner color="red">{`! ${error}`}</Banner>}{health && healthKind && <HealthSummary health={health} kind={healthKind}/>}<Box flexDirection={compact ? "column" : "row"} gap={1}>{!compact ? <><Sidebar zones={zones?.zones ?? []} scope={scope} tunnels={tunnels} selected={selected}/>{detail}</> : compactPanel === "navigation" ? <Sidebar zones={zones?.zones ?? []} scope={scope} tunnels={tunnels} selected={selected}/> : detail}</Box><Footer filtering={filtering} compact={compact} panel={compactPanel}/>{addingZone && <ZoneInput value={newZone}/>}{pendingZone && <ZoneConfirmation current={scope} next={pendingZone} remember={rememberChoice}/>}{pendingAdd && <ZoneActionConfirmation action="add" zone={pendingAdd}/>}{pendingLogin && <ZoneActionConfirmation action="login" zone={pendingLogin}/>}</Box>;
}

function Header({scope, version, listedAt}: {scope: Scope; version: string | null; listedAt: string | null}) { return <Box borderStyle="round" borderColor="cyan" paddingX={1} flexDirection="column"><Box justifyContent="space-between"><Box><Text bold color="cyan">CFTUNNEL</Text><Text dimColor>{`  Operational dashboard${version ? ` · v${version}` : ""}`}</Text></Box><Text>Scope: <Text color="magenta">{scope ?? "no registered zone"}</Text></Text></Box><Text dimColor>{`Inventory: local YAML + current systemd query${listedAt ? ` · ${listedAt}` : ""}`}</Text></Box>; }
function Summary({summary, total}: {summary: {active: number; enabled: number; inactive: number}; total: number}) { return <Box gap={1} marginY={1}><Metric label="TUNNELS" value={total} color="cyan"/><Metric label="ACTIVE" value={summary.active} color="green"/><Metric label="ENABLED" value={summary.enabled} color="yellow"/><Metric label="INACTIVE" value={summary.inactive} color="gray"/></Box>; }
function Metric({label, value, color}: {label: string; value: number; color: "cyan" | "green" | "yellow" | "gray"}) { return <Box borderStyle="round" borderColor={color} paddingX={1}><Text color={color} bold>{value} </Text><Text dimColor>{label}</Text></Box>; }
function Banner({children, color}: {children: string; color: "cyan" | "yellow" | "red"}) { return <Box borderStyle="round" borderColor={color} paddingX={1} marginBottom={1}><Text color={color}>{children}</Text></Box>; }
function HealthSummary({health, kind}: {health: Health; kind: "tunnel" | "scope"}) { return <Box marginBottom={1}><Text color="yellow">{kind === "scope" ? "SCOPE HEALTH" : "TUNNEL HEALTH"} · completed at {health.checked_at} · {health.tunnels.length} tunnel{health.tunnels.length === 1 ? "" : "s"} checked</Text></Box>; }
function Sidebar({zones, scope, tunnels, selected}: {zones: Zone[]; scope: Scope; tunnels: Tunnel[]; selected: number}) { return <Box flexDirection="column" width={43} flexShrink={0} gap={1}><Box borderStyle="round" borderColor="magenta" flexDirection="column" paddingX={1}><Text bold color="magenta">ZONES</Text>{zones.map(zone => <Box key={zone.name} flexDirection="column"><Text inverse={scope === zone.name} color={credentialColor(zone.credential.state)}>{scope === zone.name ? "›" : " "} {credentialIcon(zone.credential.state)} {zone.name}</Text><Text dimColor>{`    ${zone.tunnel_count} tunnels · ${zone.route_count} routes · ${credentialLabel(zone.credential.state)}`}</Text></Box>)}</Box><Box borderStyle="round" borderColor="blue" flexDirection="column" paddingX={1}><Text bold color="blue">TUNNELS</Text>{tunnels.length === 0 ? <Text dimColor>None in this scope</Text> : tunnels.map((tunnel, index) => <Text key={tunnelKey(tunnel)} inverse={index === selected} color={statusColor(tunnel.config.issues.length ? "failed" : tunnel.status)}>{index === selected ? "›" : " "} {statusIcon(tunnel.config.issues.length ? "failed" : tunnel.status)} {tunnel.name}</Text>)}</Box><Legend/></Box>; }
function Legend() { return <Box borderStyle="round" borderColor="gray" flexDirection="column" paddingX={1}><Text bold>LEGEND</Text><Text dimColor>● bound: zone credential validated</Text><Text dimColor>◌ unverified: binding metadata absent</Text><Text dimColor>! invalid: binding/config needs attention</Text><Text dimColor>● active: systemd running</Text><Text dimColor>○ inactive: unit stopped</Text><Text dimColor>Health is explicit and timestamped.</Text></Box>; }
function TunnelDetail({tunnel, health}: {tunnel: Tunnel; health: Health | null}) { const entry = health?.tunnels.find(item => item.name === tunnel.name && item.zone === tunnel.zone); return <Box borderStyle="round" borderColor="green" flexDirection="column" paddingX={1} flexGrow={1}><Box justifyContent="space-between"><Text bold>DETAILS · {tunnel.name}</Text><Text color={statusColor(tunnel.status)}>{statusIcon(tunnel.status)} {tunnel.status.toUpperCase()}</Text></Box><Text dimColor>{tunnel.zone} · {tunnel.unit}</Text><Box marginTop={1}><Text bold>Local configuration</Text></Box><Text>YAML: <State value={tunnel.config.yaml.present} detail={tunnel.config.yaml.mode}/>{`  credential JSON: `}<State value={tunnel.config.credential.present} detail={tunnel.config.credential.mode}/></Text><Text>Expected unit: <Text color={statusColor(tunnel.status)}>{tunnel.unit}</Text> · {tunnel.status}</Text><Text>UUID: {tunnel.uuid ?? "unresolved"} · {tunnel.routes.length} routes</Text><Diagnosis tunnel={tunnel}/><Box marginTop={1}><Text bold>Routes</Text></Box>{tunnel.routes.map(route => <Box key={route.hostname}><Text color="cyan">{route.hostname}</Text><Text dimColor>  →  {route.service}</Text></Box>)}{entry ? <HealthPanel entry={entry} checkedAt={health?.checked_at ?? ""}/> : <Box marginTop={1}><Text dimColor>Press h for this tunnel or H for the current scope health check.</Text></Box>}</Box>; }
function State({value, detail}: {value: boolean; detail: string | null}) { return <Text color={value ? "green" : "red"}>{value ? `present${detail ? ` (${detail})` : ""}` : "missing"}</Text>; }
function Diagnosis({tunnel}: {tunnel: Tunnel}) { const issues = [...tunnel.config.issues]; if (!tunnel.config.credential.present) issues.push("Restore the private tunnel credential file before starting this unit."); if (tunnel.status === "inactive") issues.push(`Unit inactive — inspect: cftunnel --zone ${tunnel.zone} status --name ${tunnel.name}`); if (tunnel.status === "failed" || tunnel.status === "unavailable") issues.push("Local systemd status could not be considered healthy; inspect the host service manager."); if (issues.length === 0) return null; return <Box borderStyle="single" borderColor="yellow" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="yellow">ATTENTION</Text>{[...new Set(issues)].map(issue => <Text key={issue}>{issue}</Text>)}</Box>; }
function HealthPanel({entry, checkedAt}: {entry: Health["tunnels"][number]; checkedAt: string}) { return <Box borderStyle="single" borderColor="yellow" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="yellow">HEALTH · {checkedAt}</Text><Text>systemd: <Text color={statusColor(entry.systemd.status)}>{entry.systemd.status}</Text> · credential: {entry.config.credential.present ? "present" : "missing"}</Text>{entry.routes.map(route => <Box key={route.hostname} flexDirection="column"><Text>DNS {route.hostname}: <Text color={route.dns.result ? "green" : "red"}>{route.dns.result ?? "unresolved"}</Text></Text>{!route.dns.result && <Text dimColor>{`Inspect: cftunnel --zone ${entry.zone} health --name ${entry.name}`}</Text>}</Box>)}</Box>; }
function EmptyState({zone, filter}: {zone: Zone | undefined | null; filter: string}) { if (filter && zone && zone.name.toLowerCase().includes(filter.toLowerCase())) return <Box borderStyle="round" borderColor="gray" paddingX={1} flexGrow={1} flexDirection="column"><Text bold>{zone.name}</Text><Text dimColor>{`Zone matches “${filter}”, but it has no local tunnels.`}</Text></Box>; if (filter) return <Box borderStyle="round" borderColor="gray" paddingX={1} flexGrow={1}><Text dimColor>No tunnel or zone matches the current filter in this scope.</Text></Box>; if (!zone) return <Box borderStyle="round" borderColor="gray" paddingX={1} flexGrow={1}><Text dimColor>No local tunnel routes found across registered zones.</Text></Box>; return <Box borderStyle="round" borderColor="gray" paddingX={1} flexGrow={1} flexDirection="column"><Text bold>{zone.name}</Text><Text dimColor>{`Registered zone · credential ${zone.credential.state} · no local tunnels configured.`}</Text></Box>; }
function ZoneConfirmation({current, next, remember}: {current: Scope; next: string; remember: boolean}) { return <Box borderStyle="double" borderColor="yellow" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="yellow">CHANGE ACTIVE ZONE</Text><Text>{`Current Scope: ${current ?? "none"}`}</Text><Text>{`New Scope:     ${next}`}</Text><Text>This also changes the CLI default zone.</Text><Text color="cyan">{`${remember ? "[x]" : "[ ]"} Do not ask again in this session (Space toggles)`}</Text><Text dimColor>[Enter] Confirm and set zone  [Esc] Cancel</Text></Box>; }
function ZoneInput({value}: {value: string}) { return <Box borderStyle="double" borderColor="cyan" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="cyan">ADD CLOUDFLARE ZONE</Text><Text>Enter the registered Cloudflare zone, not a host or route.</Text><Text color="cyan">{`Zone: ${value}▌`}</Text><Text dimColor>[Enter] Continue  [Esc] Cancel</Text></Box>; }
function ZoneActionConfirmation({action, zone}: {action: "add" | "login"; zone: string}) { const add = action === "add"; return <Box borderStyle="double" borderColor="yellow" flexDirection="column" marginTop={1} paddingX={1}><Text bold color="yellow">{add ? "ADD ZONE AND LOGIN" : "LOGIN TO ACTIVE ZONE"}</Text>{add ? <><Text>{`cftunnel zone use ${zone}`}</Text><Text dimColor>Register and set the default zone</Text><Text>{`Then: cftunnel --zone ${zone} zone login`}</Text><Text dimColor>Authenticate and save a credential to the active zone</Text></> : <><Text>{`cftunnel --zone ${zone} zone login`}</Text><Text dimColor>Authenticate and save a credential to the active zone</Text></>}<Text>{add ? "Registers the zone, makes it the Scope/default, then opens browser authentication." : "Opens browser authentication for the current Scope."}</Text><Text dimColor>[Enter] Confirm  [Esc] Cancel</Text></Box>; }
function Footer({filtering, compact, panel}: {filtering: boolean; compact: boolean; panel: "navigation" | "detail"}) { return <Box marginTop={1}><Text dimColor>{filtering ? "Type to filter by zone, name, hostname, or state · Enter accepts · Esc clears" : `${compact ? `[Tab] ${panel === "navigation" ? "details" : "navigation"}  ` : ""}[a] add zone [l] login [←→] zone [↑↓] tunnel [h] tunnel health [H] scope health [/] filter [r] refresh [q] quit`}</Text></Box>; }
function filterTunnels(tunnels: Tunnel[], filter: string) { const terms = filter.toLowerCase().trim().split(/\s+/).filter(Boolean); return tunnels.filter(tunnel => terms.every(term => [tunnel.zone, tunnel.name, tunnel.status, ...tunnel.routes.map(route => route.hostname)].some(value => value.toLowerCase().includes(term)))); }
function statusColor(status: string): "green" | "yellow" | "gray" | "red" { if (status === "active") return "green"; if (status === "enabled") return "yellow"; if (status === "inactive") return "gray"; return "red"; }
function statusIcon(status: string) { return status === "active" ? "●" : status === "enabled" ? "◐" : "○"; }
function credentialColor(state: Zone["credential"]["state"]): "green" | "yellow" | "red" { return state === "ready" ? "green" : state === "missing" ? "yellow" : "red"; }
function credentialIcon(state: Zone["credential"]["state"]) { return state === "ready" ? "●" : state === "missing" ? "◌" : "!"; }
function credentialLabel(state: Zone["credential"]["state"]) { return state === "ready" ? "bound" : state === "missing" ? "unverified" : "invalid"; }
